#!/bin/bash -e
# Delete any h5 files files generated by seticore on the blpn machines.
# Run this as obs.

for x in `seq 0 63`; do
    HOST=blpn$x
    ssh $HOST "find /scratch/data -wholename '*seticore_beamformer/*h5' -delete "
    echo did $HOST
done
